### ISSUE TITLE
Non assembly not included?

### ISSUE THREAD

**Issue by klauspost** [rleiwang/svb#2]
The package should have a pure Go fallback so it will work on other platforms.

**Comment by rleiwang** [comment]
do you mean function like this https://github.com/rleiwang/svb/blob/master/decoder.go#L21? I don't quite follow what you meant.

**Comment by klauspost** [comment]
No, pure Go implementations so your package works on non-amd64 platforms and on machines without SSSE3.

Right now it will not even compile on others since there isn't any build tags restricting access to the assembly functions.

Try `GOARCH=arm64 GOOS=linux go build .` for instance.

**Comment by aqrit** [comment]
I wrote a scalar version in C, if anyone finds that amusing...
https://gist.github.com/aqrit/f666e05362bc75376ac59a34879fad4f

**Comment by rleiwang** [comment]
@aqrit Thanks, nice work

**Comment by rleiwang** [comment]
@klauspost I added cross platform build support. Please let me know if I missed anything.

**Comment by klauspost** [comment]
Nice. Some additional build tags that can be helpful:

Add to amd64: `//+build !noasm !appengine !gccgo`

This will disable assembly on appengine and gccgo which doesn't support assembly and add the custom `noasm` tag that makes it easy to completely disable assembly.

The stubs can have the opposite: `//+build !amd64 noasm appengine gccgo`

You can test with `-tags=noasm` to see if your non-assembly version builds.

**Comment by rleiwang** [comment]
added and tested build flags https://github.com/rleiwang/svb/blob/master/stub_amd64.go#L3
